const productes = [
    {
        name : "Пицца плюс",
        img : "rest_1.png",
        time : "50min",
        rate : 4.5,
        price : 900,
        currency : "₽",
        id : 1,
    },
    {
        name : "Тануки",
        img : "rest_2.png",
        time : "50min",
        rate : 5,
        price : 1200,
        currency : "₽",
        id : 2,
    },
    {
        name : "FoodBand",
        img : "rest_3.png",
        time : "50min",
        rate : 4,
        price : 1000,
        currency : "₽",
        id : 3,
    },
    {
        name : "Жадина-пицца",
        img : "rest_4.png",
        time : "50min",
        rate : 4.3,
        price : 800,
        currency : "₽",
        id : 4,
    },
    {
        name : "Точка еды",
        img : "rest_5.png",
        time : "50min",
        rate : 3.7,
        price : 500,
        currency : "₽",
        id : 5,
    },
    {
        name : "PizzaBurger",
        img : "rest_6.png",
        time : "50min",
        rate : 4.5,
        price : 1300,
        currency : "₽",
        id : 6,
    },
];